=== ivocalado/streamadapt/streamadapt/policies/policy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="AdaptationPolicy"
	xmlns:ap="AdaptationPolicy">
	<xs:complexType name="PolicyConfigurationType">
		<xs:annotation>
			<xs:documentation>The PolicyConfigurationType type consists of a
				set of childs witch configure the entire stream properties.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="policy-name" type="xs:string"> </xs:element>
			<xs:element name="policy-description" type="xs:string"/>
			<xs:element name="startup-config">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="negotiation">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="collapse"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="transport">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="protocol">
										<xs:annotation>
											<xs:documentation>Define the protocol that will be used to
									transmission. To the adaptation be enabled, an element in
									trasnport-adaptation MUST have a same value. Otherwise, a warning will be launched
									</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
												<xs:whiteSpace value="collapse"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="plugin-name">
										<xs:annotation>
											<xs:documentation>This tag describes the plugin name to be used.
</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="library-name">
										<xs:annotation>
											<xs:documentation>Specifically, it is defined the shared library to handle transport-related things.
This property can be overhindden during infrastructure startup</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element minOccurs="0" name="library-directory">
										<xs:annotation>
											<xs:documentation>Defines the diretory to search. This value could ommited.</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element default="true" name="enable-adaptation"
										type="xs:boolean">
										<xs:annotation>
											<xs:documentation>Define if the adaptation will be enabled
								</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element minOccurs="0" name="provides">
										<xs:complexType>
											<xs:sequence maxOccurs="unbounded" minOccurs="1">
												<xs:element name="provide" type="ap:ProviderType"/>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:choice maxOccurs="unbounded" minOccurs="0">
										<xs:element name="complexproperty"
											type="ap:ComplexPropertyType"/>
										<xs:element name="simpleproperty"
											type="ap:SimplePropertyType"/>
									</xs:choice>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="stream">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="plugin-name">
										<xs:annotation>
											<xs:documentation>This tag describes the plugin name to be used.
</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="library-name">
										<xs:annotation>
											<xs:documentation>Specifically, it is defined the shared library to handle transport-related things.
This property can be overhindden during infrastructure startup</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element minOccurs="0" name="library-directory">
										<xs:annotation>
											<xs:documentation>Defines the diretory to search. This value could ommited.</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="transmission-properties">
										<xs:complexType>
											<xs:choice>
												<xs:element name="video-transmission">
												<xs:complexType>
												<xs:sequence>
												<xs:element name="video-codec" type="xs:string"/>
												</xs:sequence>
												</xs:complexType>
												</xs:element>
												<xs:element name="audio-transmission">
												<xs:complexType>
												<xs:sequence>
												<xs:element name="codec-name">
												<xs:simpleType>
												<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
												</xs:restriction>
												</xs:simpleType>
												</xs:element>
												</xs:sequence>
												<xs:attribute default="false"
												name="enable-preprocessing" type="xs:boolean"/>
												</xs:complexType>
												</xs:element>
											</xs:choice>
											<xs:attribute default="half-transmit"
												name="transmission-type">
												<xs:simpleType>
												<xs:restriction base="xs:string">
												<xs:enumeration value="half-transmit"/>
												<xs:enumeration value="half-receive"/>
												<xs:enumeration value="full-duplex"/>
												</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:complexType>
									</xs:element>
									<xs:element default="true" name="enable-adaptation"
										type="xs:boolean"/>
									<xs:element minOccurs="0" name="provides">
										<xs:complexType>
											<xs:sequence maxOccurs="unbounded" minOccurs="1">
												<xs:element name="provide" type="ap:ProviderType"/>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:choice maxOccurs="unbounded" minOccurs="0">
										<xs:element name="complexproperty"
											type="ap:ComplexPropertyType"/>
										<xs:element name="simpleproperty"
											type="ap:SimplePropertyType"/>
									</xs:choice>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element minOccurs="0" name="adapt-config">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="stream" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="adaptation-method">
										<xs:annotation>
											<xs:documentation>This node defines what adaptation-policy
									node will be used</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="0"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="policy" type="ap:PolicyType"
										maxOccurs="unbounded" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="transport" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="adaptation-method">
										<xs:annotation>
											<xs:documentation>This node defines what adaptation-policy
									node will be used</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="0"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="policy" type="ap:PolicyType"
										maxOccurs="unbounded" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="adaptation-policy" type="ap:PolicyConfigurationType">
		<xs:annotation>
			<xs:documentation>
				The policy element is a root of the Adaptation Policy XML vocabulary.
				Every conforming document should start with this element.
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="PolicyType">
		<xs:sequence>
			<xs:element name="comparisson-attibute">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="unit">
				<xs:annotation>
					<xs:documentation>Define the unit that will be used to
						measure</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element maxOccurs="1" minOccurs="0" name="lower">
				<xs:complexType>
					<xs:sequence>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element maxOccurs="1" minOccurs="1" name="complexproperty"
								type="ap:ComplexPropertyType"> </xs:element>
							<xs:element maxOccurs="1" minOccurs="1" name="simpleproperty"
								type="ap:SimplePropertyType"/>
							<xs:element name="if" type="ap:IFType"/>
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="threshold" type="xs:float" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="range">
				<xs:complexType>
					<xs:sequence>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element maxOccurs="1" minOccurs="1" name="complexproperty"
								type="ap:ComplexPropertyType"> </xs:element>
							<xs:element maxOccurs="1" minOccurs="1" name="simpleproperty"
								type="ap:SimplePropertyType"/>
							<xs:element name="if" type="ap:IFType"/>
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="from" type="xs:float" use="required">
						<xs:annotation>
							<xs:documentation>Define the left bound</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="to" type="xs:float" use="required">
						<xs:annotation>
							<xs:documentation>Define the right bound</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element minOccurs="0" name="greater">
				<xs:complexType>
					<xs:sequence>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element maxOccurs="1" minOccurs="1" name="complexproperty"
								type="ap:ComplexPropertyType"> </xs:element>
							<xs:element maxOccurs="1" minOccurs="1" name="simpleproperty"
								type="ap:SimplePropertyType"/>
							<xs:element name="if" type="ap:IFType"/>
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="threshold" type="xs:float" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ComplexPropertyType">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="sub-property"
				type="ap:SimplePropertyType"> </xs:element>
		</xs:sequence>
		<xs:attribute name="key" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="SimplePropertyType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="key" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="IFType">
		<xs:sequence maxOccurs="1">
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element name="equals">
					<xs:complexType>
						<xs:attribute form="unqualified" name="Lhs" type="xs:string" use="required"/>
						<xs:attribute name="Rhs" type="xs:float" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="lower">
					<xs:complexType>
						<xs:attribute form="unqualified" name="Lhs" type="xs:string" use="required"/>
						<xs:attribute name="Rhs" type="xs:float" use="required"/>
						<xs:attribute default="false" name="equals" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="greater">
					<xs:complexType>
						<xs:attribute form="unqualified" name="Lhs" type="xs:string" use="required"/>
						<xs:attribute name="Rhs" type="xs:float" use="required"/>
						<xs:attribute default="false" name="equals" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:element name="operations">
				<xs:complexType>
					<xs:choice maxOccurs="unbounded" minOccurs="0">
						<xs:element name="simpleproperty" type="ap:SimplePropertyType"/>
						<xs:element name="complexproperty" type="ap:ComplexPropertyType"/>
					</xs:choice>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ProviderType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="default-value" type="xs:double" use="required"/>
				<xs:attribute default="1000" name="update-time" type="xs:unsignedInt">
					<xs:annotation>
						<xs:documentation>This field should be informed to inform the infrastructure the update time in miliseconds needed for this information. 
The default value is 1000 miliseconds</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== ivocalado/streamadapt/streamadapt/policies/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<adaptation-policy xmlns="AdaptationPolicy"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="AdaptationPolicy file:/home/ivocalado/workspace/streamadapt/streamadapt/policies/policy.xsd">
    <policy-name xmlns="">politica Teste</policy-name>
    <policy-description xmlns="">O objetivo desta politica Ã© realizar testes com o plugin de transporte</policy-description>
    <startup-config xmlns="">
        <negotiation>negotiation0</negotiation>
        <transport>
            <protocol>DCCP</protocol>
            <plugin-name>DCCPSocketPlugin</plugin-name>
            <library-name>libplugins-transport.so</library-name>
            <library-directory>/home/ivocalado/workspace/streamadapt/plugins-transport/Debug/</library-directory>
            <enable-adaptation>true</enable-adaptation>
             
             <provides>
                 <provide default-value="2.6" update-time="1000">RTT</provide>
                 <provide default-value="30" update-time="500">bandwidt</provide>
             </provides>
            
            <simpleproperty key="SDESItem">rtpsend demo app.</simpleproperty>
            <simpleproperty key="ExpireTimeout">1000000</simpleproperty>
            <simpleproperty key="PayloadFormat">0</simpleproperty>
            <simpleproperty key="SchedulingTimeout">10000</simpleproperty>
        </transport>
        <stream>
            <plugin-name>SpeexPlugin</plugin-name>
            <library-name>libplugins-stream.so</library-name>
            <library-directory>/home/ivocalado/workspace/streamadapt/plugins-stream/Debug/</library-directory>
            <transmission-properties transmission-type="full-duplex">
                <audio-transmission enable-preprocessing="true">
                    <codec-name>WideBand</codec-name>
                </audio-transmission>
            </transmission-properties>
            <enable-adaptation>false</enable-adaptation>            
        </stream>
    </startup-config>
    <!-- 
    <adapt-config xmlns="">
        <transport>
            <adaptation-method>qpolicy</adaptation-method>
            <policy>
                <comparisson-attibute>RTT</comparisson-attibute>
                <lower threshold="2.5">
                    <if>
                        <equals Lhs="bandwidt" Rhs="30.0"/>
                        <operations>
                            <simpleproperty key="DCCPTXCCID">5</simpleproperty>
                        </operations>
                    </if>
                    <simpleproperty key="PayloadFormat">1</simpleproperty>
                </lower>
            </policy>
        </transport>
    </adapt-config>
    -->
</adaptation-policy>

=== ivocalado/streamadapt/trunk/streamadapt/policies/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<adaptation-policy xmlns="AdaptationPolicy"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="AdaptationPolicy file:/home/ivocalado/workspace/streamadapt/policies/policy.xsd">
    <policy-name xmlns="">politica Teste</policy-name>
    <policy-description xmlns="">O objetivo desta politica Ã© realizar testes com o plugin de transporte</policy-description>
    <startup-config xmlns="">
        <negotiation>negotiation0</negotiation>
        <transport>
            <protocol>DCCP</protocol>
            <plugin-name>DCCPSocketPlugin</plugin-name>
            <library-name>libplugins-transport.so</library-name>
            <library-directory>/home/ivocalado/workspace/plugins-transport/Debug/</library-directory>
            <enable-adaptation>true</enable-adaptation>
            <provides>
                <provide default-value="3.6">RTT</provide>
                <provide default-value="10.5">bandwidt</provide>
            </provides>
            
            <simpleproperty key="SDESItem">rtpsend demo app.</simpleproperty>
            <simpleproperty key="ExpireTimeout">1000000</simpleproperty>
            <simpleproperty key="PayloadFormat">0</simpleproperty>
            <simpleproperty key="SchedulingTimeout">10000</simpleproperty>
        </transport>
        <stream>
            <plugin-name>fdg</plugin-name>
            <library-name>uyt</library-name>
            <transmission-properties transmission-type="full-duplex">
                <audio-transmission>
                    <codec-name>jh</codec-name>
                </audio-transmission>
            </transmission-properties>
            
            <enable-adaptation>false</enable-adaptation>            
        </stream>
    </startup-config>
    <adapt-config xmlns="">
        <transport>
            <adaptation-method>qpolicy</adaptation-method>
            <policy>
                <comparisson-attibute>RTT</comparisson-attibute>
                <unit>seconds</unit>
                <lower threshold="2.5">
                    <if>
                        <equals Lhs="bandwidt" Rhs="30.0"/>
                        <operations>
                            <simpleproperty key="DCCPTXCCID">5</simpleproperty>
                        </operations>
                    </if>
                    <simpleproperty key="PayloadFormat">1</simpleproperty>
                </lower>
            </policy>
        </transport>
    </adapt-config>
</adaptation-policy>
